version : "3"
services:
  application:
    container_name: ViewIt-webapp
    depends_on:
      - database
    build: .
    ports:
      - "8888:8080"
    volumes:
      - ./Docker/webapp/properties/jdbc.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/jdbc.properties
      - ./Docker/webapp/properties/images.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/images.properties
      - ./data/filmImages/:/data/filmImages/
  database:
    container_name: ViewIt-database
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Docker/database/sql:/docker-entrypoint-initdb.d