version : "3"
services:
  application:
    container_name: ViewIt-webapp
    image: registry.gitlab.com/hei-projet/hei-projet-2020/site-viewit
    #build: .
    depends_on:
      - database
    ports:
      - "8888:8080"
    volumes:
      - ./Docker/webapp/properties/jdbc.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/jdbc.properties
      - ./Docker/webapp/properties/images.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/images.properties
      - ./data/filmImages/:/data/filmImages/
  database:
    container_name: ViewIt-database
    image: mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Docker/database/sql:/docker-entrypoint-initdb.d